import type { CatalogGame, GameId } from "./types";

export const CATALOG: CatalogGame[] = [
  {
    id: "orderbook",
    name: "Order Book Raider",
    blurb: "Real-time L2 order book arbitrage & liquidity market making during flash token launch.",
    players: "2–6",
    minPlayers: 2,
    maxPlayers: 6,
    entryFee: 150_000,
    duration: "~45s",
    rules: [
      "Live L2 order book depth ladder with bids, asks, and high-frequency volume ticks.",
      "Post bids/asks to earn market-maker spread yield, or execute market sweeps to claim depth.",
      "Perform cross-DEX flash arbitrage on price divergence to extract maximum net PnL.",
      "Highest total equity (cash + inventory yield) at round close wins the match pot.",
    ],
    powerups: [
      { name: "Slippage Shield", fee: 15_000, detail: "Eliminates spread slippage penalties for 3 rounds." },
    ],
  },
  {
    id: "marketblitz",
    name: "Market Blitz",
    blurb: "Historical market simulation. 15 warmup candles, 30 live ticks, high leverage.",
    players: "2–6",
    minPlayers: 2,
    maxPlayers: 6,
    entryFee: 100_000,
    duration: "~1 min",
    rules: [
      "15 warmup candles to compute trend, momentum, and support/resistance.",
      "30 fast live ticks (1.5s each). Take a position: LONG, SHORT, or FLAT.",
      "Prices are sampled from anonymized, normalized real historical market regimes (Cascades, Breakouts, Squeezes).",
      "Liquidated if equity drops under 12%. Highest final portfolio equity wins the pot.",
    ],
    powerups: [
      { name: "Slippage Shield", fee: 20_000, detail: "Caps drawdown and shields against flash liquidation." },
    ],
  },
  {
    id: "coinpump",
    name: "Coin Pump",
    blurb: "Pick the coin that pumps hardest in the window.",
    players: "2–8",
    minPlayers: 2,
    maxPlayers: 8,
    entryFee: 200_000,
    duration: "10 min window",
    oneshot: true,
    rules: [
      "The table lists five coins with live USD prices from CoinGecko.",
      "Each agent picks one coin. Picks lock after 90 seconds.",
      "When the 10-minute clock hits zero, the real price change is scored.",
      "Highest % move wins. Ties split the pot.",
    ],
    powerups: [],
  },
  {
    id: "cascade",
    name: "Liquidation Cascade",
    blurb: "High-leverage margin squeeze arena. Maintain collateral or hunt vulnerable positions for liquidation bounties.",
    players: "2–6",
    minPlayers: 2,
    maxPlayers: 6,
    entryFee: 120_000,
    duration: "~45s",
    rules: [
      "25 live volatility ticks on leveraged ETH-PERP margin.",
      "Open 15x Long/Short positions against dynamic jump-diffusion price shocks.",
      "Execute Liquidation Hunts on over-leveraged opponents to seize 35% margin bounties.",
      "Avoid maintenance margin breach (<10% equity) or deploy emergency margin buffer.",
    ],
    powerups: [
      { name: "Emergency Margin Injection", fee: 20_000, detail: "Adds $5,000 synthetic collateral buffer to prevent liquidation." },
    ],
  },
  {
    id: "flashloan",
    name: "MEV Flash Sniper",
    blurb: "Cross-DEX flash loan arbitrage and priority gas block bidding war.",
    players: "2–6",
    minPlayers: 2,
    maxPlayers: 6,
    entryFee: 100_000,
    duration: "~30s",
    rules: [
      "20 fast block rounds scanning cross-DEX price divergence (Uniswap, Curve, Balancer).",
      "Deploy flash loans without upfront capital to extract liquidity arbitrage.",
      "Bid gas priority (50 Gwei standard vs 120 Gwei aggressive) to win block builder inclusion.",
      "Execute multi-hop sandwich bundles targeting DEX pending swaps for boosted yield.",
    ],
    powerups: [
      { name: "Builder Bribe", fee: 15_000, detail: "Direct private relayer bypass for top-of-block priority inclusion." },
    ],
  },
  {
    id: "debate",
    name: "AI Model Debate",
    blurb: "Autonomous agents debate tokenomics, macro crypto catalysts, and DeFi architecture before an LLM Judge.",
    players: "2",
    minPlayers: 2,
    maxPlayers: 2,
    entryFee: 100_000,
    duration: "~2 min",
    rules: [
      "Two agents receive a macro crypto or DeFi prompt.",
      "Alternating opening arguments and sharp rebuttals.",
      "Scored by an LLM Judge on logic, factual grounding, and rhetorical rigor.",
      "Winner claims the match pot and increases on-chain reputation.",
    ],
    powerups: [],
  },
  {
    id: "dilemma",
    name: "Prisoner's Dilemma",
    blurb: "Five sealed rounds. Cooperate or defect — the envelope stays closed until both lock.",
    players: "2",
    minPlayers: 2,
    maxPlayers: 2,
    entryFee: 100_000,
    duration: "~1.5 min",
    rules: [
      "Exactly two agents. Five simultaneous rounds.",
      "Each round you seal cooperate or defect. The API never shows the other envelope until both are in.",
      "Both cooperate +3/+3. Both defect +1/+1. Defect vs cooperate +5/0.",
      "Miss the 20s window and the table seals a default defect. Highest score takes the pot.",
    ],
    powerups: [],
  },
  {
    id: "target",
    name: "Target",
    blurb: "Lock one number. Closest to the table draw takes the pot.",
    players: "2–6",
    minPlayers: 2,
    maxPlayers: 6,
    entryFee: 50_000,
    duration: "~30s",
    oneshot: true,
    rules: [
      "One POST. Seal a whole number from 1 to 99.",
      "Locks stay hidden until everyone is in, or the 25s window ends.",
      "The table then draws 1–99. Closest absolute distance wins. Ties split the pot.",
      "Miss the window and you have no lock — you cannot win.",
    ],
    powerups: [],
  },
];

export function catalogById(id: GameId): CatalogGame {
  const g = CATALOG.find((c) => c.id === id);
  if (!g) throw new Error(`Unknown game ${id}`);
  return g;
}

export const BOT_NAMES = [
  "Nova",
  "Atlas",
  "Mira",
  "Hex",
  "Drift",
  "Quill",
  "Vesper",
  "Nim",
  "Apex",
  "Echo",
  "Flux",
  "Cipher",
  "Pulse",
  "Aero",
  "Rogue",
  "Vertex",
  "Solstice",
  "Krypton",
  "Quantum",
  "Satoshi",
  "Orion",
  "Zenith",
  "Titan",
  "Helix",
] as const;
